# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-21 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Author_Book_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='age',
        ),
    ]
