# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LaR_app', '0002_message'),
        ('books_app', '0002_auto_20180325_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='users',
        ),
        migrations.AddField(
            model_name='review',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to='LaR_app.User'),
            preserve_default=False,
        ),
    ]
